# **Parquet / Arvo / ORC (optimised row columnar)**

**Basic parquet format file handling**

In [2]:
import pyarrow.parquet as parquet_parsor

In [3]:
parquet_data = parquet_parsor.read_table('/content/drive/MyDrive/Ex_Files_Data_Ingestion_Python/Exercise Files/Ch02/02_03/taxi.parquet')

In [4]:
parquet_data

pyarrow.Table
VendorID: int64
tpep_pickup_datetime: timestamp[us]
tpep_dropoff_datetime: timestamp[us]
passenger_count: int64
trip_distance: double
RatecodeID: int64
store_and_fwd_flag: string
PULocationID: int64
DOLocationID: int64
payment_type: int64
fare_amount: double
extra: double
mta_tax: double
tip_amount: double
tolls_amount: double
improvement_surcharge: double
total_amount: double

In [5]:
import pandas as pd

pd_df = parquet_data.to_pandas()

In [7]:
pd_df

      VendorID tpep_pickup_datetime  ... improvement_surcharge  total_amount
0            2  2018-10-31 07:10:55  ...                   0.3         20.54
1            2  2018-10-31 16:38:25  ...                   0.3         13.80
2            2  2018-10-31 20:23:41  ...                   0.3         11.30
3            2  2018-10-31 22:44:24  ...                   0.3          5.80
4            2  2018-10-31 23:22:18  ...                   0.3         13.56
...        ...                  ...  ...                   ...           ...
9995         2  2018-11-01 11:04:03  ...                   0.3          6.80
9996         2  2018-11-01 11:04:05  ...                   0.3         13.00
9997         2  2018-11-01 11:04:06  ...                   0.3         14.80
9998         1  2018-11-01 11:04:08  ...                   0.3         13.55
9999         1  2018-11-01 11:04:08  ...                   0.3          7.80

[10000 rows x 17 columns]

In [8]:
pd_df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   int64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
dtype: object